version: '3'
networks:
    edu-net:
        driver: bridge
services:
    tornado:
        build: .
        ports:
          - "8000:8000"
          - "8001:8001"
        networks:
            - edu-net
        restart: always
    mysql:
        container_name: mysql
        image: mariadb:10.4
        ports:
            - 3307:3306
        environment:
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - ./scripts:/docker-entrypoint-initdb.d/
        restart: always
        networks:
            - edu-net
    redis:
        container_name: redis
        image: redis:5.0.7
        ports:
            - 6380:6379
        environment:
            MYSQL_ROOT_PASSWORD: root
        restart: always
        networks:
            - edu-net